#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc rule -r "*"

bspc config border_width                  2
bspc config split_ratio                   0.5

bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config window_gap                    0

bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config single_monocle                false
bspc config gapless_monocle               true

bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true

bcpc config remove_unplugged_monitors     true

bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

bspc config pointer_follows_monitor       true
bspc config click_to_focus                true

bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

bspc config normal_border_color           "#3c3836"
bspc config active_border_color           "#1e1e1e"
bspc config focused_border_color          "#fabd2f"
bspc config presel_feedback_color         "#83a598"
bspc config urgent_border_color           "#fb4934"

# commande `xprop | grep WM_CLASS`
#
bspc rule -a vlc desktop=^4 state=fullscreen follow=on
bspc rule -a Gimp-2.10 desktop=^4 follow=on state=floating
bspc rule -a Why3 state=floating


bash $HOME/git/scripts/keyboard_config &
bash $HOME/git/scripts/monitor_on_boot &

killall "xfce4-power-manager" ; xfce4-power-manager &
killall "udiskie"             ; udiskie &
killall "sxhkd"               ; sxhkd &
killall "dunst"               ; dunst &

for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar &
done
